### ISSUE TITLE
Incompatibility with reeses sodium options

### ISSUE THREAD

**Issue by MaxedOut1** [Adrenix/Nostalgic-Tweaks#6] opened 2022-04-04 19:19 UTC
This mod adds extra settings options to video settings with sodium. Including features for settings that optifine has. It crashes on startup.

**Comment by LonelySauce** [comment] 2022-04-28 08:55
I can confirm this: https://pastebin.com/qbHDq3Qu

**Comment by LonelySauce** [comment] 2022-04-30 12:25
You still need to fix this issue, telling players to disable something in the mod config is not intuitive and will make people not want to use the mod. A good thing to keep in mind is that 90% of the Minecraft player base does not know how to report bugs to their respective mod authors and are not willing to do so (mostly because of general laziness and/or lack of knowledge as said before).

I would just remove the old cloud height config option if it's causing a startup crash since, like you said before, Sodium Extras fills in that role very neatly.

**Comment by LonelySauce** [comment] 2022-04-30 13:54
Also, what setting in the json file do I need to change in order to fix this myself?

**Comment by Adrenix** [comment] 2022-04-30 17:15
I never said I wasn't going to fix this issue... I offered a temporary solution to the problem until I can find time to work on the mod again. I work on this mod for free so development happens whenever I have the time to do so.

The easiest temporary solution is **removing** Sodium Extras. If you want to keep that mod then setting `"oldCloudHeight": true` to `"oldCloudHeight": false` _might_ let the game start. If it doesn't then you will have to wait until I can develop a permanent fix.

**Comment by LonelySauce** [comment] 2022-04-30 19:51
> I never said I wasn't going to fix this issue... I offered a temporary solution to the problem until I can find time to work on the mod again. I work on this mod for free so development happens whenever I have the time to do so.
> 
> The easiest temporary solution is **removing** Sodium Extras. If you want to keep that mod then setting `"oldCloudHeight": true` to `"oldCloudHeight": false` _might_ let the game start. If it doesn't then you will have to wait until I can develop a permanent fix.

Sorry if I sounded hostile back there, that message was poorly composed due to me acting like a pessimist for no reason. It could be because of something else but I still cannot figure out why I was in a such a shitty mood.

**Comment by Adrenix** [comment] 2022-04-30 20:33
Don't worry about it, it's fine.

I am still learning the do's and don'ts with mixins so the fix may be simple (or complex). I'm sorry to hear that the config option didn't work. The next update I do will be focused on patching up compatibility issues. 👍

**Comment by MaxedOut1** [comment] 2022-05-02 18:00
Hey, just an update. Like lonelysauce said, it is actually sodium extra which causes the issues (sodium extra depends on reeses sodium options). Disabling anything in the config doesnt make a difference. Thanks!

**Comment by Adrenix** [comment] 2022-05-17 19:25
This issue is now fixed in v1.0.3.

**Closed by Adrenix** 2022-05-17 19:25 UTC
Labels: bug, investigate, startup crash
