### ISSUE TITLE
[FORGE] The game crashes when Splash Potions are thrown when this mod is installed

### ISSUE THREAD

**Issue by Daralexen05** [Adrenix/Nostalgic-Tweaks#57] opened 2024-02-11 06:45 UTC
## Version Information
Minecraft Version: 1.20.1
Forge Version: Latest release for 1.20.1
Nostalgic Tweaks Version: NostalgicTweaks-1.20.1-Forge-2.0.0-Beta-8.4.1

## Describe the Bug
Whenever a Splash Potion is thrown, there is a chance that the game will crash due to being unable to render it properly. It can be from a player, Witch, or any modded entity that uses Splash Potions. 

## Crash Report
> The report states that Nostalgic Tweaks is susceptible for causing the crash.
https://pastebin.com/kTcTngp8

## Bug Context
> I was fighting a group of Zombies and a Witch in hopes of trapping the Witch in a boat in order to have a way to cure Zombie Villagers without the need to go to The Nether. Since I have an Enhanced AI installed, the Witch threw splash potions at the Zombies to buff them while she kept her distance. She threw Fire Resistance (which is not even necessary due to Mob Sunscreen being installed) and Regeneration. She threw a third potion, but the game crashed before I could see it. The game crashed again as soon as I opened the world again. This also happens when I use Splash Potions sometimes in Creative Mode.

## Screenshots
> N/A

**Comment by Daralexen05** [comment] 2024-02-11 23:19
It also causes crashes when normal potions are dropped on the ground as entities. Maybe it is my resource pack, but I have had no issues using it without Nostalgic Tweaks.

**Comment by Adrenix** [comment] 2024-03-04 16:25
It's not the fault of a resource pack. Looks like an issue caused by Optifine.

**Comment by Daralexen05** [comment] 2024-03-10 03:04
Update on the issue. I have received similar crashes caused by an arrow being shot by either a Piglin or Wither Skeleton with Enhanced AI installed.

**Comment by Adrenix** [comment] 2024-07-12 05:10
This should be fixed in beta 9.

**Closed by Adrenix** 2024-07-12 05:10 UTC
Labels: bug, forge
