### ISSUE TITLE
[FORGE] Game crashing after trying to edit settings

### ISSUE THREAD

**Issue by PlatFrog** [Adrenix/Nostalgic-Tweaks#55] opened 2024-02-01 23:28 UTC
## Version Information

Minecraft Version: 1.20.1
Forge Version: (NeoForge 47.1.96)
Nostalgic Tweaks Version: 2.0.0 Beta 8.4.1

## Describe the Bug

When I attempt to open the settings, the game just crashes

## Crash Report

[crash-2024-02-01_18.23.57-client.txt](https://github.com/Adrenix/Nostalgic-Tweaks/files/14132137/crash-2024-02-01_18.23.57-client.txt)

## Bug Context

The game was fine yesterday, I have no idea why this is happening now, I did not add any mod or modify any file.

## Screenshots
> If applicable, add screenshots to help explain your problem.
N/a

**Comment by Adrenix** [comment] 2024-03-04 16:30
Looks like an issue caused by the VisualOverhaul mod. Try turning off the iconic buttons in their config and see if that helps.

**Comment by Adrenix** [comment] 2024-08-07 20:57
This should be fixed in beta 9.

**Closed by Adrenix** 2024-08-07 20:57 UTC
Labels: bug, forge
